const_value = 1

	const DEX_BULBASAUR  ; 1
	const DEX_IVYSAUR    ; 2
	const DEX_VENUSAUR   ; 3
	const DEX_CHARMANDER ; 4
	const DEX_CHARMELEON ; 5
	const DEX_CHARIZARD  ; 6
	const DEX_SQUIRTLE   ; 7
	const DEX_WARTORTLE  ; 8
	const DEX_BLASTOISE  ; 9
	const DEX_CATERPIE   ; 10
	const DEX_METAPOD    ; 11
	const DEX_BUTTERFREE ; 12
	const DEX_WEEDLE     ; 13
	const DEX_KAKUNA     ; 14
	const DEX_BEEDRILL   ; 15
	const DEX_PIDGEY     ; 16
	const DEX_PIDGEOTTO  ; 17
	const DEX_PIDGEOT    ; 18
	const DEX_RATTATA    ; 19
	const DEX_RATICATE   ; 20
	const DEX_SPEAROW    ; 21
	const DEX_FEAROW     ; 22
	const DEX_EKANS      ; 23
	const DEX_ARBOK      ; 24
	const DEX_PIKACHU    ; 25
	const DEX_RAICHU     ; 26
	const DEX_SANDSHREW  ; 27
	const DEX_SANDSLASH  ; 28
	const DEX_NIDORAN_F  ; 29
	const DEX_NIDORINA   ; 30
	const DEX_NIDOQUEEN  ; 31
	const DEX_NIDORAN_M  ; 32
	const DEX_NIDORINO   ; 33
	const DEX_NIDOKING   ; 34
	const DEX_CLEFAIRY   ; 35
	const DEX_CLEFABLE   ; 36
	const DEX_VULPIX     ; 37
	const DEX_NINETALES  ; 38
	const DEX_JIGGLYPUFF ; 39
	const DEX_WIGGLYTUFF ; 40
	const DEX_ZUBAT      ; 41
	const DEX_GOLBAT     ; 42
   const DEX_CROBAT     ; 43
	const DEX_ODDISH     ; 44
	const DEX_GLOOM      ; 45
	const DEX_VILEPLUME  ; 46
   const DEX_BELLOSSOM  ; 47
	const DEX_PARAS      ; 48
	const DEX_PARASECT   ; 49
	const DEX_VENONAT    ; 50
	const DEX_VENOMOTH   ; 51
	const DEX_DIGLETT    ; 52
	const DEX_DUGTRIO    ; 53
	const DEX_MEOWTH     ; 54
	const DEX_PERSIAN    ; 55
	const DEX_PSYDUCK    ; 56
	const DEX_GOLDUCK    ; 57
	const DEX_MANKEY     ; 58
	const DEX_PRIMEAPE   ; 59
	const DEX_GROWLITHE  ; 60
	const DEX_ARCANINE   ; 61
	const DEX_POLIWAG    ; 62
	const DEX_POLIWHIRL  ; 63
	const DEX_POLIWRATH  ; 64
   const DEX_POLITOED   ; 65
	const DEX_ABRA       ; 66
	const DEX_KADABRA    ; 67
	const DEX_ALAKAZAM   ; 68
	const DEX_MACHOP     ; 69
	const DEX_MACHOKE    ; 70
	const DEX_MACHAMP    ; 71
	const DEX_BELLSPROUT ; 72
	const DEX_WEEPINBELL ; 73
	const DEX_VICTREEBEL ; 74
	const DEX_TENTACOOL  ; 75
	const DEX_TENTACRUEL ; 76
	const DEX_GEODUDE    ; 77
	const DEX_GRAVELER   ; 78
	const DEX_GOLEM      ; 79
	const DEX_PONYTA     ; 80
	const DEX_RAPIDASH   ; 81
	const DEX_SLOWPOKE   ; 82
	const DEX_SLOWBRO    ; 83
   const DEX_SLOWKING   ; 84
	const DEX_MAGNEMITE  ; 85
	const DEX_MAGNETON   ; 86
   const DEX_MAGNEZONE  ; 87
	const DEX_FARFETCHD  ; 88
	const DEX_DODUO      ; 89
	const DEX_DODRIO     ; 90
	const DEX_SEEL       ; 91
	const DEX_DEWGONG    ; 92
	const DEX_GRIMER     ; 93
	const DEX_MUK        ; 94
	const DEX_SHELLDER   ; 95
	const DEX_CLOYSTER   ; 96
	const DEX_GASTLY     ; 97
	const DEX_HAUNTER    ; 98
	const DEX_GENGAR     ; 99
	const DEX_ONIX       ; 100
   const DEX_STEELIX    ; 101
	const DEX_DROWZEE    ; 102
	const DEX_HYPNO      ; 103
	const DEX_KRABBY     ; 104
	const DEX_KINGLER    ; 105
	const DEX_VOLTORB    ; 106
	const DEX_ELECTRODE  ; 107
	const DEX_EXEGGCUTE  ; 108
	const DEX_EXEGGUTOR  ; 109
	const DEX_CUBONE     ; 110
	const DEX_MAROWAK    ; 111
	const DEX_HITMONLEE  ; 112
	const DEX_HITMONCHAN ; 113
	const DEX_LICKITUNG  ; 114
   const DEX_LICKILICKY ; 115
	const DEX_KOFFING    ; 116
	const DEX_WEEZING    ; 117
	const DEX_RHYHORN    ; 118
	const DEX_RHYDON     ; 119
   const DEX_RHYPERIOR  ; 120
	const DEX_CHANSEY    ; 121
   const DEX_BLISSEY    ; 122
	const DEX_TANGELA    ; 123
   const DEX_TANGROWTH  ; 124
	const DEX_KANGASKHAN ; 125
	const DEX_HORSEA     ; 126
	const DEX_SEADRA     ; 127
   const DEX_KINGDRA    ; 128
	const DEX_GOLDEEN    ; 129
	const DEX_SEAKING    ; 130
	const DEX_STARYU     ; 131
	const DEX_STARMIE    ; 132
	const DEX_MR_MIME    ; 133
	const DEX_SCYTHER    ; 134
   const DEX_SCIZOR     ; 135
   const DEX_SMOOCHUM   ; 136
	const DEX_JYNX       ; 137
   const DEX_ELEKID     ; 138
	const DEX_ELECTABUZZ ; 139
   const DEX_ELECTIVIRE ; 140
   const DEX_MAGBY      ; 141
	const DEX_MAGMAR     ; 142
   const DEX_MAGMORTAR  ; 143
	const DEX_PINSIR     ; 144
	const DEX_TAUROS     ; 145
	const DEX_MAGIKARP   ; 146
	const DEX_GYARADOS   ; 147
	const DEX_LAPRAS     ; 148
	const DEX_DITTO      ; 149
	const DEX_EEVEE      ; 150
	const DEX_VAPOREON   ; 151
	const DEX_JOLTEON    ; 152
	const DEX_FLAREON    ; 153
   const DEX_ESPEON     ; 154
   const DEX_UMBREON    ; 155
   const DEX_LEAFEON    ; 156
   const DEX_GLACEON    ; 157
   const DEX_SYLVEON    ; 158
	const DEX_PORYGON    ; 159
   const DEX_PORYGON2   ; 160
   const DEX_PORYGON_Z  ; 161
	const DEX_OMANYTE    ; 162
	const DEX_OMASTAR    ; 163
	const DEX_KABUTO     ; 164
	const DEX_KABUTOPS   ; 165
	const DEX_AERODACTYL ; 166
	const DEX_SNORLAX    ; 167
	const DEX_ARTICUNO   ; 168
	const DEX_ZAPDOS     ; 169
	const DEX_MOLTRES    ; 170
	const DEX_DRATINI    ; 171
	const DEX_DRAGONAIR  ; 172
	const DEX_DRAGONITE  ; 173
	const DEX_MEWTWO     ; 174
	const DEX_MEW        ; 175

NUM_POKEMON    EQU 175
