MoveNames::
	db "POUND@"
	db "KARATE CHOP@"
	db "DOUBLESLAP@"
	db "COMET PUNCH@"
	db "BUG BITE@"
	db "PAY DAY@"
	db "FIRE PUNCH@"
	db "ICE PUNCH@"
	db "THUNDERPUNCH@"
	db "SCRATCH@"
	db "X-SCISSOR@"
	db "MEGAHORN@"
	db "SILVER WIND@"
	db "SWORDS DANCE@"
	db "CUT@"
	db "GUST@"
	db "WING ATTACK@"
	db "WHIRLWIND@"
	db "FLY@"
	db "SIGNAL BEAM@"
	db "BUG BUZZ@"
	db "VINE WHIP@"
	db "STOMP@"
	db "DOUBLE KICK@"
	db "QUIVER DANCE@"
	db "JUMP KICK@"
	db "FEINT ATTACK@"
	db "SAND-ATTACK@"
	db "HEADBUTT@"
	db "HORN ATTACK@"
	db "NIGHT SLASH@"
	db "CRUNCH@"
	db "TACKLE@"
	db "BODY SLAM@"
	db "SNARL@"
	db "TAKE DOWN@"
	db "THRASH@"
	db "DOUBLE-EDGE@"
	db "TAIL WHIP@"
	db "POISON STING@"
	db "TWINEEDLE@"
	db "PIN MISSILE@"
	db "LEER@"
	db "BITE@"
	db "GROWL@"
	db "ROAR@"
	db "SING@"
	db "SUPERSONIC@"
	db "SONICBOOM@"
	db "DISABLE@"
	db "ACID@"
	db "EMBER@"
	db "FLAMETHROWER@"
	db "MIST@"
	db "WATER GUN@"
	db "HYDRO PUMP@"
	db "SURF@"
	db "ICE BEAM@"
	db "BLIZZARD@"
	db "PSYBEAM@"
	db "BUBBLEBEAM@"
	db "DARK PULSE@"
	db "HYPER BEAM@"
	db "PECK@"
	db "DRILL PECK@"
	db "NASTY PLOT@"
	db "LOW KICK@"
	db "COUNTER@"
	db "SEISMIC TOSS@"
	db "STRENGTH@"
	db "ABSORB@"
	db "MEGA DRAIN@"
	db "LEECH SEED@"
	db "GROWTH@"
	db "RAZOR LEAF@"
	db "TAUNT@"
	db "POISONPOWDER@"
	db "STUN SPORE@"
	db "SLEEP POWDER@"
	db "PETAL DANCE@"
	db "STRING SHOT@"
	db "SPIKES@"
	db "DRAGON CLAW@"
	db "THUNDERSHOCK@"
	db "THUNDERBOLT@"
	db "THUNDER WAVE@"
	db "THUNDER@"
	db "ROCK THROW@"
	db "EARTHQUAKE@"
	db "DRAGON RUSH@"
	db "DIG@"
	db "TOXIC@"
	db "CONFUSION@"
	db "PSYCHIC@"
	db "HYPNOSIS@"
	db "MEDITATE@"
	db "AGILITY@"
	db "OUTRAGE@"
	db "TWISTER@"
	db "TELEPORT@"
	db "NIGHT SHADE@"
	db "MIMIC@"
	db "SCREECH@"
	db "DOUBLE TEAM@"
	db "RECOVER@"
	db "HARDEN@"
	db "MINIMIZE@"
	db "SMOKESCREEN@"
	db "CONFUSE RAY@"
	db "WITHDRAW@"
	db "DEFENSE CURL@"
	db "BARRIER@"
	db "LIGHT SCREEN@"
	db "HAZE@"
	db "REFLECT@"
	db "SHOCK WAVE@"
	db "DRAGONBREATH@"
	db "DRAGON PULSE@"
	db "DRAGON DANCE@"
	db "SPARK@"
	db "THUNDER FANG@"
	db "LICK@"
	db "SMOG@"
	db "SLUDGE@"
	db "WILD CHARGE@"
	db "FIRE BLAST@"
	db "WATERFALL@"
	db "VOLT TACKLE@"
	db "SWIFT@"
	db "DISCHARGE@"
	db "PLAY ROUGH@"
	db "DISARM VOICE@"
	db "AMNESIA"
	db "FAIRY WIND"
	db "SOFTBOILED@"
	db "HI JUMP KICK@"
	db "GLARE@"
	db "DREAM EATER@"
	db "POISON GAS@"
	db "DRAININGKISS@"
	db "LEECH LIFE@"
	db "LOVELY KISS@"
	db "MOONBLAST@"
	db "TRANSFORM@"
	db "BUBBLE@"
	db "DIZZY PUNCH@"
	db "SPORE@"
	db "DAZZLE GLEAM@"
	db "FORCE PALM@"
	db "SPLASH@"
	db "ACID ARMOR@"
	db "CRABHAMMER@"
	db "BRICK BREAK@"
	db "FURY SWIPES@"
	db "BONEMERANG@"
	db "REST@"
	db "ROCK SLIDE@"
	db "HYPER FANG@"
	db "SHARPEN@"
	db "CONVERSION@"
	db "TRI ATTACK@"
	db "SUPER FANG@"
	db "SLASH@"
	db "SUBSTITUTE@"
	db "STRUGGLE@"
	db "DRAIN PUNCH@"
	db "CLOSE COMBAT@"
	db "SUPERPOWER@"
	db "AURA SPHERE@"
	db "FOCUS BLAST@"
	db "FIRE FANG@"
	db "FLARE BLITZ@"
	db "FLAME CHARGE@"
	db "FLAME WHEEL@"
	db "BLAZE KICK@" ; 175
	db "FLAME BURST@"
	db "HEAT WAVE@"
	db "WILL-O-WISP@"
	db "AERIAL ACE@"
	db "BRAVE BIRD@"
	db "AIR CUTTER@"
	db "AIR SLASH@"
	db "HURRICANE@"
	db "ROOST@"
	db "ASTONISH@" ; 185
	db "CHARM@"
	db "SHADOW PUNCH@"
	db "SHADOW CLAW@"
	db "PHANTOMFORCE@"
	db "OMINOUS WIND@"
	db "SHADOW BALL@"
	db "BULLET SEED@"
	db "SEED BOMB@"
	db "LEAF BLADE@"
	db "POWER WHIP@" ; 195
	db "MAGICAL LEAF@"
	db "GIGA DRAIN@"
	db "ENERGY BALL@"
	db "SYNTHESIS@"
	db "BONE RUSH@"
	db "BULLDOZE@"
	db "DRILL RUN@"
	db "MUD SLAP@"
	db "MUD BOMB@"
	db "EARTH POWER@" ; 205
	db "FREEZE DRY@"
	db "ICICLE SPEAR@"
	db "ICE FANG@"
	db "ICICLE CRASH@"
	db "POWDER SNOW@"
	db "ICY WIND@"
	db "HYPER VOICE@"
	db "PROTECT@"
	db "POISON FANG@"
	db "CROSS POISON@" ; 215
	db "POISON JAB@"
	db "GUNK SHOT@"
	db "SLUDGE BOMB@"
	db "COIL@"
	db "PSYCHO CUT@"
	db "ZEN HEADBUTT@"
	db "EXTRASENSORY@"
	db "CALM MIND@"
	db "MIRROR COAT@"
	db "ROCK BLAST@" ; 225
	db "ROCK TOMB@"
	db "STONE EDGE@"
	db "HEAD SMASH@"
	db "ANCIENTPOWER@"
	db "POWER GEM@"
	db "ROCK POLISH@"
	db "METAL CLAW@"
	db "STEEL WING@"
	db "IRON HEAD@"
	db "IRON TAIL@" ; 235
	db "MIRROR SHOT@"
	db "FLASH CANNON@"
	db "IRON DEFENSE@"
	db "RAZOR SHELL@"
	db "AQUA TAIL@"
	db "WATER PULSE@"
	db "SCALD@"
	db "RAPID SPIN@"
	db "STEALTH ROCK@"
	db "TOXIC SPIKES@" ; 245
	db "DEFOG@"
	db "VACUUM WAVE@"       ; F7
	db "QUICK ATTACK@"      ; F8
	db "AQUA JET@"          ; F9
	db "ICE SHARD@"         ; FA
	db "SHADOW SNEAK@"      ; FB
	db "BULLET PUNCH@"      ; FC
	db "MACH PUNCH@"        ; FD
	db "EXTREMESPEED@"      ; FE


